---
githubrepo:
  - name: "webHookTest"
    file: ".*"
    action:
      name: argprint
      args:
      - arg1
      - arg2
  - name: "MetricsAtHome"
    file: ".*"
    action:
      name: argprint
      args:



